### ISSUE TITLE
LLM node can't find model locations

### ISSUE THREAD

**Issue by wardensc2** [Big-Idea-Technology/ComfyUI_LLM_Node#2]
Hi Big Idea Technology

I already installed  your node and also create LLM checkpoints folder but so far the node cant find the checkpoint. What should I do

Please support me, thank you so much

![image](https://github.com/Big-Idea-Technology/ComfyUI_LLM_Node/assets/77379748/c2e147e9-15cb-4051-8ade-d4a659158902)

**Comment by nazgut** [comment]
Hey,

are you created folder ComfyUI/models/LLM_checkpoints ? Also do you click refresh after downloading model?

**Comment by wardensc2** [comment]
I create both folder since I use ComfyUI portable version I have 2 ComfyUI folders but your node still does not find the model in both cases. Here are 2 folders location:

![image](https://github.com/Big-Idea-Technology/ComfyUI_LLM_Node/assets/77379748/8c30c6e1-9e85-402c-8a21-b37ff6f3d1d4)

![image](https://github.com/Big-Idea-Technology/ComfyUI_LLM_Node/assets/77379748/24720943-9695-4bec-8e62-85188f491cff)

![image](https://github.com/Big-Idea-Technology/ComfyUI_LLM_Node/assets/77379748/0712d3e1-eeba-4348-bde8-48784447d959)

Please have a look, thank you.

**Comment by nazgut** [comment]
but you need to download whole folder from huggingface not only model file.
![Zrzut ekranu z 2024-04-08 10-31-45](https://github.com/Big-Idea-Technology/ComfyUI_LLM_Node/assets/2010343/a02098a5-611d-4e40-8006-f0309990a345)
![Zrzut ekranu z 2024-04-08 10-32-36](https://github.com/Big-Idea-Technology/ComfyUI_LLM_Node/assets/2010343/62e41bab-f448-43b4-b2f4-acdd53b85d91)

**Comment by nazgut** [comment]
![Zrzut ekranu z 2024-04-08 10-32-36](https://github.com/Big-Idea-Technology/ComfyUI_LLM_Node/assets/2010343/a3827794-b07d-4b8b-b205-8a2ff29cb60a)

**Comment by nazgut** [comment]
![Zrzut ekranu z 2024-04-08 10-33-41](https://github.com/Big-Idea-Technology/ComfyUI_LLM_Node/assets/2010343/920c19bc-bb2b-43c3-94c7-dc3438060264)

**Comment by wardensc2** [comment]
> ![Zrzut ekranu z 2024-04-08 10-33-41](https://private-user-images.githubusercontent.com/2010343/320410535-920c19bc-bb2b-43c3-94c7-dc3438060264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjY0MDcsIm5iZiI6MTcxMjU2NjEwNywicGF0aCI6Ii8yMDEwMzQzLzMyMDQxMDUzNS05MjBjMTliYy1iYjJiLTQzYzMtOTRjNy1kYzM0MzgwNjAyNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMDg0ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQzOWZmMDViMWY0MGY0YWQ2MDFhNDE5NmUwZDQ3NWQxNzk0NGZkM2UxYTcyMzgwNmVhYmNhYmIxNGRiMGVkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wpw2M2Q0HQxVh444x2DwJkf2582t2QuW9udfxtHxo7I)

It's working thank you so much
